#!/bin/sh

newpsk=$(httpd -m $(cat))

if [ ! -z ${newpsk} ]; then
  cat > /root/httpd/httpd.conf << EOF
/:admin:${newpsk}
EOF
fi

echo "Content-Type: text/plain"
echo "Content-Length: 2"
echo "Date: $(date -u +"%a, %d %b %Y %H:%M:%S GMT")"
echo ""
echo -n "OK"

if [ ! -z ${newpsk} ]; then
  killall httpd
fi
