#!/bin/sh

if [ -f /root/wg_common.sh ]; then
  . /root/wg_common.sh
fi

if [ ! -f /etc/wireguard/wg0.conf ]; then
  cat > /etc/wireguard/wg0.conf << EOF
[Interface]
PrivateKey = $(wg genkey)
Address = 192.168.1.1/32
MTU = 1280
EOF
  wg_reload wg0 > /dev/null 2>&1
fi

cat /etc/wireguard/wg0.conf | grep -v PrivateKey | cat > /tmp/wg0.conf

echo "Content-Type: text/plain"
echo "Content-Length: $(stat -c %s /tmp/wg0.conf)"
echo "Date: $(date -u +"%a, %d %b %Y %H:%M:%S GMT")"
echo ""

cat /tmp/wg0.conf

rm -rf /tmp/wg0.conf > /dev/null 2>&1
